#!/bin/sh
#
# This script fills the TACO database with the content of the resource
# files found in the directory pointed by $RES_BASE_DIR and its subdirs
#
# It may substitute the current db_fillup program, which may only used
# with the GDBM.
#
# The database server has to been started.
#
# Author(s):	Jens Krueger
#		$Author: jkrueger1 $
#
# Date:		$Date: 2004-04-29 11:02:31 $
#
# Version:	$Revision: 1.1 $
#
# Copyright (c) 2004, FRM-II, TU Munich, Germany
#
if test -z "$RES_BASE_DIR" ; then
	echo "RES_BASE_DIR environment variable is not set"
	exit 1
fi
for i in `ls -R1p $RES_BASE_DIR | grep -v '/$' | grep -v '^$'`; do
	if echo $i | grep ':$' >/dev/null ; then
		dir=`basename ${i%:}`
		continue
	fi
	if ! db_update $dir/$i ; then
		echo ERROR during update the $RES_BASE_DIR/$dir/$i resource file.
	else
		echo Resources sucessfully imported from : $RES_BASE_DIR/$dir/$i 
	fi
done
