#!/bin/sh
#
# agps.startup : starts the TACO AGPS C++ device server and menu
#

# setup TACO environment variables

. ./taco
. ./test/$sysconfdir/tacoenv.sh

echo "Starting AGPS device server ..." >>log 2>&1
test/$bindir/AGPSpp 1 >>log 2>&1 &
sleep 1
echo "Starting AGPS menu ..." >>log 2>&1
echo 4 > .agps
echo 0 >>.agps
test/$bindir/ps_menu test/agps/1>>log 2>&1 <.agps 
sleep 1
rm .agps

killall AGPSpp >>log 2>&1
