#! /bin/sh
i=0 
export NETHOST=${NETHOST:-`hostname`}
pers_name=`uname -n|cut -f1 -d'.'` 
while test $i -lt 1000 ; do 
	echo $i  
	./db_devlist startserver/$pers_name
	i=`expr $i + 1`  
	usleep 100000
done
