#!/bin/sh

. ./taco
. ./test/$sysconfdir/tacoenv.sh

killall Inst_verify
sleep 1
killall Manager
dc_destdir=`pwd`/test
make -C .. DESTDIR=$dc_destdir uninstall >/dev/null 2>&1
dir=`echo $prefix | cut -d'/' -f 1`
if [ -z "$dir" ] ; then
	dir=`echo $prefix | cut -d'/' -f 2`
fi
rm -rf ${dc_destdir}/$dir
dir=`aclocal --print-ac-dir | cut -d'/' -f 1`
if [ -z "$dir" ] ; then
	dir=`aclocal --print-ac-dir | cut -d'/' -f 2`
fi
rm -rf ${dc_destdir}/$dir
if { rmdir test; } ; then
	exit 0
fi
exit 1
