#! /bin/sh
i=0 
export NETHOST=${NETHOST:-`hostname`}
while test $i -lt 1000 ; do 
	echo $i
	./db_resput test/device/2/res1 TEST	
	../system/dbase/tools/db_resdel test/device/2/res1
	i=`expr $i + 1`  
	usleep 100000
done
