#! /bin/sh
. ./taco
. ./test/$sysconfdir/tacoenv.sh

if { ! ./db_connect ; } ; then exit 77 ; fi
a=`./db_resfamily test 2>log | tr '[:lower:]' '[:upper:]'`
b=`echo "device" | tr '[:lower:]' '[:upper:]'`
echo $a > .tmp
echo $b >> .tmp
if [ `uniq .tmp | wc -l` -ne 1 ] ; then rm .tmp; exit 2 ; fi
rm .tmp
exit 0
