#!/bin/sh

##############################################################
#
#  off - script to kill all processes with specified name
#
##############################################################

case $# in
0)	echo "$0 usage : $0 <process name>";exit
esac

###########################################
# kills all processes with name $proc_name

kill_procs()
{
  PSARGS="auxc"

  number_of_procs=`ps $PSARGS | grep -v $0 | grep -v grep | grep $proc_name | wc -l`
  pid_list=`ps $PSARGS | grep -v grep | grep -v $0 | grep $proc_name | awk '{print $2}'`
  echo "There are $number_of_procs $proc_name processes:"

  for i in $pid_list
  do	
    echo "Killing process $i"
    kill $i
  done

  echo ""
}

############################################
# main script

proc_name=$1 ; kill_procs
