#! /bin/sh

### BEGIN INIT INFO
# Provides: taco
# Required-Start: $network $portmap
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the TACO system services.
### END INIT INFO

. /etc/rc.status
rc_reset

taco_config_file="/etc/tacoenv.sh"
if test -f "$taco_config_file" ; then
	. "$taco_config_file" 
else
	echo "error: TACO configuration file '$taco_config_file' not installed"
	rc_failed
	rc_exit
fi

usage="Usage: $0 {start|stop|status|restart|new}"
taco_manager="$DSHOME/system/bin/linux/x86/Manager"

case $1 in
	start)
		if test ! -f "$DBM_DIR/names.pag" ; then
			echo "Initialization of the database:"
			if db_fillup 0 ; then
				rc_status -v
			else
				rc_status -v
				rc_exit
			fi
		fi
		if test "x$TACO_SECURE_MODE" = xyes ; then
			echo -n "Starting TACO services in secure mode"
			/sbin/startproc -s -t 5 -q "$taco_manager" -security
			rc_status -v
		else
			echo -n "Starting TACO services"
			/sbin/startproc -s -q "$taco_manager"
			rc_status -v
		fi
		;;
	stop)
		echo -n "Shutting down TACO services"
		/sbin/killproc "$taco_manager"
		rc_status -v
		;;
	restart)
		$0 stop
		$0 start $2
		rc_status
		;;
	status)
		echo -n "Checking for TACO services"
		/sbin/checkproc "$taco_manager"
		rc_status -v
		;;
	new)
		echo -n "Do you really want to delete the complete TACO database (not the resource files)? (yes/no): "
		read
		if test "x$REPLY" = xyes ; then
			rm "$DBM_DIR"/*
			$0 restart $2
			rc_status
		else
			rc_failed
		fi
		;;
	*)
		echo "$usage"
		rc_failed
		;;
esac
rc_exit
