/*static char RcsId[] = "$Header: /home/jkrueger1/sources/taco/backup/taco/bindings/labview/server/LabViewGeneric.h,v 1.1 2004-01-26 08:44:22 hgilde1 Exp $ ";*/
/*********************************************************************
 *
 * File:	LabViewGeneric.h
 *
 * Project:	Device Server Distribution
 *
 * Description:	Dummy class to test control system installations
 *		
 *
 * Author(s):	J.Meyer
 *
 * Original:	10.5.95
 *
 * Revision 1.1  2000/02/01 11:14:09  goetz
 * Initial revision
 *
 * Revision 4.2  96/03/20  16:32:04  16:32:04  meyer (Jens Meyer)
 * Added RCS header to menu.
 * 
 * Revision 4.1  96/03/18  19:15:57  19:15:57  meyer (Jens Meyer)
 * Small modifications.
 * 
 *
 * Copyright(c) 1994 by European Synchrotron Radiation Facility, 
 *                     Grenoble, France
 *
 * File generated by the Automatic Class Generation Tool,  2.4 
 * (Thu May 11 15:07:11 1995).
 *
 *********************************************************************/

#ifndef _LabViewGeneric_H
#define _LabViewGeneric_H



/*************************************************************************
 * Include here the file which contains the definition of DevLabViewGenericBase,
 * may be  CntrlDsNumbers.h, DasDsNumbers.h or BlcDsNumbers.h.
 * See DSN096.
 *************************************************************************
*/

#include <Frm2DsNumbers.h>

typedef struct _LabViewGenericClassRec *LabViewGenericClass;
typedef struct _LabViewGenericRec *LabViewGeneric;

extern LabViewGenericClass labViewGenericClass;

#define DevGetViInfo				DevLabViewGenericBase+1
#define DevGetControlList 		DevLabViewGenericBase+2
#define DevGetControlInfo 		DevLabViewGenericBase+3
#define DevSetControlValue		DevLabViewGenericBase+4
#define DevGetIndicatorList	DevLabViewGenericBase+5
#define DevGetIndicatorInfo	DevLabViewGenericBase+6


#define DevErr_LVCannotLoadLibrary	DevLabViewGenericBase + 1


#define LVGetViInfo				1
#define LVGetControlList		2
#define LVGetControlInfo		3
#define LVSetControlValue		4
#define LVGetIndicatorList		5
#define LVGetIndicatorInfo		6
#define LVState					7
#define LVStatus					8

#endif /*_LabViewGeneric_H*/
