/*static char RcsId[] = "$Header: /home/jkrueger1/sources/taco/backup/taco/bindings/labview/server/LabView.h,v 1.1 2006-11-21 16:38:19 jkrueger1 Exp $ ";*/
/*********************************************************************
 *
 * File:	LabView.h
 *
 * Project:	Device Server Distribution
 *
 * Description:	Dummy class to test control system installations
 *		
 *
 * Author(s):	J.Meyer
 *
 * Original:	10.5.95
 *
 * $Log: not supported by cvs2svn $
 * Revision 1.1  2000/02/01 11:14:09  goetz
 * Initial revision
 *
 * Revision 4.2  96/03/20  16:32:04  16:32:04  meyer (Jens Meyer)
 * Added RCS header to menu.
 * 
 * Revision 4.1  96/03/18  19:15:57  19:15:57  meyer (Jens Meyer)
 * Small modifications.
 * 
 *
 * Copyright(c) 1994 by European Synchrotron Radiation Facility, 
 *                     Grenoble, France
 *
 * File generated by the Automatic Class Generation Tool,  2.4 
 * (Thu May 11 15:07:11 1995).
 *
 *********************************************************************/

#ifndef _LabView_H
#define _LabView_H



/*************************************************************************
 * Include here the file which contains the definition of DevLabViewBase,
 * may be  CntrlDsNumbers.h, DasDsNumbers.h or BlcDsNumbers.h.
 * See DSN096.
 *************************************************************************
#include <CntrlDsNumbers.h>
*/

typedef struct _LabViewClassRec *LabViewClass;
typedef struct _LabViewRec *LabView;

extern LabViewClass labViewClass;

#define DevLVIODouble 		DevLabViewBase+1
#define DevLVIOString 		DevLabViewBase+2

#define DevErr_LVCannotLoadLibrary	DevLabViewBase + 1

#define LVIOString		1
#define LVIODouble		2
#define LVReadValue		3
#define LVSetValue		4
#define LVState			5
#define LVStatus		6

#endif /*_LabView_H*/
