/*static char RcsId[] = "$Header: /home/jkrueger1/sources/taco/backup/taco/bindings/labview/server/LabViewP.h,v 1.1 2006-11-21 16:38:19 jkrueger1 Exp $";*/

/*********************************************************************
 *
 * File:	LabViewP.h
 *
 * Project:	Device Server Distribution
 *
 * Description:	Dummy class to test control system installations
 *
 * Author(s):	J.Meyer
 *
 * Original:	10.5.95	
 *
 * $Log: not supported by cvs2svn $
 * Revision 1.1  2000/02/01 11:14:09  goetz
 * Initial revision
 *
 * Revision 4.2  96/03/20  16:32:04  16:32:04  meyer (Jens Meyer)
 * Added RCS header to menu.
 * 
 * Revision 4.1  96/03/18  19:15:57  19:15:57  meyer (Jens Meyer)
 * Small modifications.
 * 
 * 
 * Copyright (c) 1994 by European Synchrotron Radiation Facility, 
 *                     Grenoble, France
 *
 * File generated by the Automatic Class Generation Tool,  2.4 
 * (Thu May 11 15:07:12 1995).
 *
 *********************************************************************/

#ifndef _LabViewP_H
#define _LabViewP_H



typedef struct _LabViewClassPart
{
		DevLong	config_param; /* Configuration parameter for hardware */
} LabViewClassPart;



typedef struct _LabViewPart
{
		DevFloat	read_value; /* Read value of device */
		DevFloat	set_value; /* Set value of the device */
} LabViewPart;



typedef struct _LabViewClassRec
{
   DevServerClassPart	devserver_class;
				
   LabViewClassPart	LabView_class;
} LabViewClassRec;



extern LabViewClassRec labViewClassRec;


typedef struct _LabViewRec
{
   DevServerPart 	devserver;
				
   LabViewPart 	LabView;
} LabViewRec;

#endif /*_LabViewP_H*/

