/*static char RcsId[] = "$Header: /home/jkrueger1/sources/taco/backup/taco/bindings/labview/server/LabViewGenericP.h,v 1.1 2004-01-26 08:44:22 hgilde1 Exp $";*/

/*********************************************************************
 *
 * File:	LabViewGenericP.h
 *
 * Project:	Device Server Distribution
 *
 * Description:	Dummy class to test control system installations
 *
 * Author(s):	J.Meyer
 *
 * Original:	10.5.95	
 *
 * Revision 1.1  2000/02/01 11:14:09  goetz
 * Initial revision
 *
 * Revision 4.2  96/03/20  16:32:04  16:32:04  meyer (Jens Meyer)
 * Added RCS header to menu.
 * 
 * Revision 4.1  96/03/18  19:15:57  19:15:57  meyer (Jens Meyer)
 * Small modifications.
 * 
 * 
 * Copyright (c) 1994-2014 by European Synchrotron Radiation Facility,
 *                     Grenoble, France
 *
 * File generated by the Automatic Class Generation Tool,  2.4 
 * (Thu May 11 15:07:12 1995).
 *
 *********************************************************************/

#ifndef _LabViewGenericP_H
#define _LabViewGenericP_H



typedef struct _LabViewGenericClassPart
{
		DevLong	config_param; /* Configuration parameter for hardware */
} LabViewGenericClassPart;



typedef struct _LabViewGenericPart
{
		DevFloat	read_value; /* Read value of device */
		DevFloat	set_value; /* Set value of the device */
} LabViewGenericPart;



typedef struct _LabViewGenericClassRec
{
   DevServerClassPart	devserver_class;
				
   LabViewGenericClassPart	LabViewGeneric_class;
} LabViewGenericClassRec;



extern LabViewGenericClassRec labViewClassRec;


typedef struct _LabViewGenericRec
{
   DevServerPart 	devserver;
				
   LabViewGenericPart 	LabViewGeneric;
} LabViewGenericRec;

#endif /*_LabViewGenericP_H*/

