/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by Builder Xcessory 4.0
 * Generated by Code Generator Xcessory 2.0 (09/09/96)
 *
 */
#ifndef xdev_const_H
#define xdev_const_H
#define XDEV_OK 0
#define GUI_HELP_VERS_BB 13
#define GUI_ERROR_WINDOW 17
#define GUI_MEMBER_TEXT 5
#define GUI_DEVINFO_NAME_TEXT 8
#define GUI_IMPORT_FORM 2
#define GUI_INARG_FORMAT_TEXT 19
#define GUI_IMPORT_SELBOX 6
#define GUI_DEVINFO_BB 7
#define GUI_DEVINFO_CLASS_TEXT 9
#define GUI_DEVINFO_SERVNAME_TEXT 11
#define GUI_INARG_VAL_TEXT 21
#define GUI_NB_SCROLL_OUT_LINES 50
#define GUI_MAX_NB_OUT_LINES 550
#define GUI_DEVINFO_HOST_TEXT 12
#define GUI_TIMEOUT_SELBOX 16
#define GUI_PROTOCOL_RB 22
#define XDEV_NOTOK -1
#define GUI_COMMAND_SELBOX 15
#define GUI_DOMAIN_TEXT 3
#define GUI_INARG_WIN 18
#define GUI_FAMILY_TEXT 4
#define GUI_DEVINFO_TYPE_TEXT 10
#define GUI_INARG_NAME_TEXT 20
#define GUI_HELP_VERS_TEXT 14
#define GUI_TCP_TB 23
#define GUI_UDP_TB 24
#define GUI_MAIN_RESULT_TEXT 1
#define GUI_MAIN_ROW_COL 0
#define XDEV_MAX_DEV 30
#define XDEV_SIG_CONF_UNDEF  -1
#endif
