######################################################################
# Automatically generated by qmake (1.06c) Fri Jan 9 12:55:54 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += LabviewClient.h Pixmaps.h TacoSilvia.h
SOURCES += LabviewClient.cpp main.cpp TacoSilvia.cpp
