/*static char RcsId[] = "$Header: /home/jkrueger1/sources/taco/backup/taco/bindings/python/python.h,v 1.1 2003-03-18 16:54:16 jkrueger1 Exp $ ";*/
/*********************************************************************
 *
 * File:	Python.h
 *
 * Project:	<PROJECT>
 *
 * Description:	<CLASSDESC>
 *		
 *
 * Author(s):	<AUTHOR>
 *
 * Original:	<DATE>
 *
 * $Log: not supported by cvs2svn $
 * Revision 2.7  2002/03/06  15:35:04  15:35:04  meyer (J.Meyer)
 * Corrected version numbering
 * 
 * Revision 2.5  2001/10/17  18:42:59  18:42:59  meyer (J.Meyer)
 * Corrected command ececution for LINUX
 * 
 * Revision 2.4  2001/07/18  16:14:02  16:14:02  meyer (J.Meyer)
 * Corrected dev_getresource().
 * 
 * Revision 2.2  2001/04/27  14:37:17  14:37:17  meyer (J.Meyer)
 * Corrected modules to work only with one shared library
 * 
 * Revision 2.1  2001/02/22  16:58:02  16:58:02  meyer (J.Meyer)
 * TACO server and client as one package!
 * 
 * Revision 1.9  2000/07/20  17:10:07  17:10:07  meyer (J.Meyer)
 * Cleaned-up sources
 * 
 * Revision 1.7  2000/06/23  15:50:09  15:50:09  meyer (J.Meyer)
 * Added methode to read command name string to Server.c
 * 
 * Revision 1.6  2000/06/22  13:09:57  13:09:57  meyer (Jens MEYER)
 * Can handle several Python classes
 * 
 * Revision 1.2  2000/06/16  18:26:24  18:26:24  meyer (Jens MEYER)
 * First running version
 * 
 * Revision 1.1  2000/06/08  12:15:11  12:15:11  meyer (Jens MEYER)
 * Initial revision
 * 
 *
 * Copyright(c) 1994 by European Synchrotron Radiation Facility, 
 *                     Grenoble, France
 *
 * File generated by the Automatic Class Generation Tool, <REVISION>
 * (<GENERATIONDATE>).
 *
 *********************************************************************/

#ifndef _PYTHON_H
#define _PYTHON_H


#define DevErr_PythonException			999
#define DevErr_PythonDataConversionError	998


typedef struct _PythonClassRec *PythonClass;
typedef struct _PythonRec *Python;

extern PythonClass pythonClass;

#endif /*_PYTHON_H*/
