/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * Builder Xcessory 4.0
 * Code Generator Xcessory 2.0 (09/09/96)
 *
 */
#include <Xm/Xm.h>
#include <Xm/MainW.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/BulletinB.h>
#include <Xm/PushB.h>
#include <Xm/Separator.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include <Xm/MessageB.h>
#include <Xm/Form.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/SelectioB.h>
#include <Xm/Label.h>
#include <Xm/CascadeB.h>
#include <Xm/PanedW.h>

/*
 * Globally included information.
 */


/*
 * Common constant and pixmap declarations.
 */
#include "xdev_const.h"

/*
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer DOUBLE(double);
extern XtPointer SINGLE(float);
extern void MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char**);
extern void SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal*, Pixel);

/*
 * Declarations for callbacks and handlers.
 */
void cb_protocol_change(Widget, XtPointer, XtPointer);
void ccb_save_widget_id(Widget, XtPointer, XtPointer);
void cb_protocol_entry(Widget, XtPointer, XtPointer);
void ccb_confirm_messbox(Widget, XtPointer, XtPointer);
void BxExitCB(Widget, XtPointer, XtPointer);
void BxUnmanageCB(Widget, XtPointer, XtPointer);
void BxManageCB(Widget, XtPointer, XtPointer);
void cb_execute_cmd_input(Widget, XtPointer, XtPointer);
void ccb_timeout_prompt(Widget, XtPointer, XtPointer);
void cb_change_timeout(Widget, XtPointer, XtPointer);
void ccb_error_messbox(Widget, XtPointer, XtPointer);
void ccb_help_version_text(Widget, XtPointer, XtPointer);
void ccb_cmd_sel_box(Widget, XtPointer, XtPointer);
void cb_execute_cmd(Widget, XtPointer, XtPointer);
void cb_close_device(Widget, XtPointer, XtPointer);
void ccb_dev_import_selbox(Widget, XtPointer, XtPointer);
void cb_fill_dev_selbox(Widget, XtPointer, XtPointer);
void cb_device_import(Widget, XtPointer, XtPointer);
void ccb_file_cb(Widget, XtPointer, XtPointer);
void cb_dev_info(Widget, XtPointer, XtPointer);
void cb_specified_cmd(Widget, XtPointer, XtPointer);
void cb_prompt_timeout(Widget, XtPointer, XtPointer);
void cb_unset_rpc_protocol(Widget, XtPointer, XtPointer);

/*
 * Create the mainWindow hierarchy of widgets.
 */
Widget
CreatemainWindow(Widget parent)
{
    Arg      args[256];
    Cardinal ac=0;
    Cardinal cdc=0;
    Boolean  argok=False;
    Widget   mainWindow;
    Widget   protocolDS;
    Widget   protocolBB;
    Widget   cancelPB1;
    Widget   setPB;
    Widget   protocolSEP;
    Widget   protocolRBox;
    Widget   tcpTB;
    Widget   udpTB;
    Widget   confirmExitDS;
    Widget   confirmExitMessBox;
    Widget   in_argDS;
    Widget   inarg_form;
    Widget   cancelPB;
    Widget   helpPB;
    Widget   executePB;
    Widget   inarg_value_sw;
    Widget   inarg_value_text;
    Widget   in_name_text;
    Widget   help_dataDS;
    Widget   help_dataBB;
    Widget   help_data_dismissPB;
    Widget   help_dataText;
    Widget   ch_timeoutDS;
    Widget   ch_timeout_selbox;
    Widget   help_appliDS;
    Widget   help_appliBB;
    Widget   help_appliSW;
    Widget   help_appli_text;
    Widget   appli_dismissPB;
    Widget   errorDS;
    Widget   errorMessBox;
    Widget   help_versionDS;
    Widget   help_versionBB;
    Widget   version_dismissPB;
    Widget   help_versionText;
    Widget   dev_infoDS;
    Widget   dev_infoBB;
    Widget   dismissPB;
    Widget   dev_infoSep;
    Widget   svc_hostText;
    Widget   svc_hostLabel;
    Widget   svc_nameText;
    Widget   svc_nameLabel;
    Widget   dev_typeText;
    Widget   dev_typeLabel;
    Widget   dev_classText;
    Widget   dev_classLabel;
    Widget   dev_nameText;
    Widget   dev_nameLabel;
    Widget   commandDS;
    Widget   commandSelBox;
    Widget   confirmCloseDS;
    Widget   confirmCloseMessBox;
    Widget   dev_importDS;
    Widget   dev_importForm;
    Widget   dev_import_SelBox;
    Widget   dev_importSep;
    Widget   dev_filterForm;
    Widget   memberText;
    Widget   familyText;
    Widget   domainText;
    Widget   memberLabel;
    Widget   familyLabel;
    Widget   domainLabel;
    Widget   menuBar;
    Widget   fileCB;
    Widget   filePDM;
    Widget   importPB;
    Widget   closePB;
    Widget   exitPB;
    Widget   viewCB;
    Widget   viewPDM;
    Widget   dev_infoPB;
    Widget   commandCB;
    Widget   commandPDM;
    Widget   statusPB;
    Widget   statePB;
    Widget   ch_timeoutPB;
    Widget   ch_protocolPB;
    Widget   helpCB;
    Widget   helpPDM;
    Widget   on_versionPB;
    Widget   on_appliPB;
    Widget   mainPW;
    Widget   mainSW;
    Widget   mainRC;
    Widget   main_resultSW;
    Widget   main_resultText;
    
    /*
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent)); 
    XtInitializeWidgetClass(xmMainWindowWidgetClass);
    XtInitializeWidgetClass(xmDialogShellWidgetClass);
    XtInitializeWidgetClass(xmBulletinBoardWidgetClass);
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
    XtInitializeWidgetClass(xmSeparatorWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmToggleButtonWidgetClass);
    XtInitializeWidgetClass(xmMessageBoxWidgetClass);
    XtInitializeWidgetClass(xmFormWidgetClass);
    XtInitializeWidgetClass(xmScrolledWindowWidgetClass);
    XtInitializeWidgetClass(xmTextWidgetClass);
    XtInitializeWidgetClass(xmSelectionBoxWidgetClass);
    XtInitializeWidgetClass(xmLabelWidgetClass);
    XtInitializeWidgetClass(xmSelectionBoxWidgetClass);
    XtInitializeWidgetClass(xmFormWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmCascadeButtonWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    XtInitializeWidgetClass(xmPanedWindowWidgetClass);
    XtInitializeWidgetClass(xmRowColumnWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 617); ac++;
    XtSetArg(args[ac], XmNy, 33); ac++;
    XtSetArg(args[ac], XmNwidth, 574); ac++;
    XtSetArg(args[ac], XmNheight, 599); ac++;
    mainWindow = XmCreateMainWindow(parent,
        "mainWindow",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 574); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    menuBar = XmCreateMenuBar(mainWindow,
        "menuBar",
        args, 
        ac);
    XtManageChild(menuBar);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 41); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    fileCB = XmCreateCascadeButton(menuBar,
        "fileCB",
        args, 
        ac);
    XtManageChild(fileCB);
    ccb_file_cb(fileCB, (XtPointer)0, (XtPointer)0);
    
    ac = 0;
    filePDM = XmCreatePulldownMenu(XtParent(fileCB),
        "filePDM",
        args, 
        ac);
    
    ac = 0;
    importPB = XmCreatePushButton(filePDM,
        "importPB",
        args, 
        ac);
    XtManageChild(importPB);
    XtAddCallback(importPB, XmNactivateCallback, BxManageCB, (XtPointer)"dev_importForm");
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    closePB = XmCreatePushButton(filePDM,
        "closePB",
        args, 
        ac);
    XtManageChild(closePB);
    XtAddCallback(closePB, XmNactivateCallback, BxManageCB, (XtPointer)"confirmCloseMessBox");
    
    ac = 0;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    exitPB = XmCreatePushButton(filePDM,
        "exitPB",
        args, 
        ac);
    XtManageChild(exitPB);
    XtAddCallback(exitPB, XmNactivateCallback, BxManageCB, (XtPointer)"confirmExitMessBox");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, filePDM); ac++;
    XtSetValues(fileCB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 46); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 48); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    viewCB = XmCreateCascadeButton(menuBar,
        "viewCB",
        args, 
        ac);
    XtManageChild(viewCB);
    
    ac = 0;
    viewPDM = XmCreatePulldownMenu(XtParent(viewCB),
        "viewPDM",
        args, 
        ac);
    
    ac = 0;
    dev_infoPB = XmCreatePushButton(viewPDM,
        "dev_infoPB",
        args, 
        ac);
    XtManageChild(dev_infoPB);
    XtAddCallback(dev_infoPB, XmNactivateCallback, cb_dev_info, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, viewPDM); ac++;
    XtSetValues(viewCB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Commands", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 94); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 94); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    commandCB = XmCreateCascadeButton(menuBar,
        "commandCB",
        args, 
        ac);
    XtManageChild(commandCB);
    
    ac = 0;
    commandPDM = XmCreatePulldownMenu(XtParent(commandCB),
        "commandPDM",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    statusPB = XmCreatePushButton(commandPDM,
        "statusPB",
        args, 
        ac);
    XtManageChild(statusPB);
    XtAddCallback(statusPB, XmNactivateCallback, cb_specified_cmd, (XtPointer)"DevStatus");
    
    ac = 0;
    XtSetArg(args[ac], XmNmnemonic, 't'); ac++;
    XtSetArg(args[ac], XmNrecomputeSize, False); ac++;
    statePB = XmCreatePushButton(commandPDM,
        "statePB",
        args, 
        ac);
    XtManageChild(statePB);
    XtAddCallback(statePB, XmNactivateCallback, cb_specified_cmd, (XtPointer)"DevState");
    
    ac = 0;
    ch_timeoutPB = XmCreatePushButton(commandPDM,
        "ch_timeoutPB",
        args, 
        ac);
    XtManageChild(ch_timeoutPB);
    XtAddCallback(ch_timeoutPB, XmNactivateCallback, cb_prompt_timeout, (XtPointer)0);
    
    ac = 0;
    ch_protocolPB = XmCreatePushButton(commandPDM,
        "ch_protocolPB",
        args, 
        ac);
    XtManageChild(ch_protocolPB);
    XtAddCallback(ch_protocolPB, XmNactivateCallback, cb_unset_rpc_protocol, (XtPointer)0);
    XtAddCallback(ch_protocolPB, XmNactivateCallback, BxManageCB, (XtPointer)"protocolBB");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, commandPDM); ac++;
    XtSetValues(commandCB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNlabelString, 
        CONVERT(parent, "Help", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 522); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 47); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    helpCB = XmCreateCascadeButton(menuBar,
        "helpCB",
        args, 
        ac);
    XtManageChild(helpCB);
    
    ac = 0;
    helpPDM = XmCreatePulldownMenu(XtParent(helpCB),
        "helpPDM",
        args, 
        ac);
    
    ac = 0;
    on_versionPB = XmCreatePushButton(helpPDM,
        "on_versionPB",
        args, 
        ac);
    XtManageChild(on_versionPB);
    XtAddCallback(on_versionPB, XmNactivateCallback, BxManageCB, (XtPointer)"help_versionBB");
    
    ac = 0;
    on_appliPB = XmCreatePushButton(helpPDM,
        "on_appliPB",
        args, 
        ac);
    XtManageChild(on_appliPB);
    XtAddCallback(on_appliPB, XmNactivateCallback, BxManageCB, (XtPointer)"help_appliBB");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, helpPDM); ac++;
    XtSetValues(helpCB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 574); ac++;
    XtSetArg(args[ac], XmNheight, 565); ac++;
    mainPW = XmCreatePanedWindow(mainWindow,
        "mainPW",
        args, 
        ac);
    XtManageChild(mainPW);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAUTOMATIC); ac++;
    XtSetArg(args[ac], XmNwidth, 568); ac++;
    XtSetArg(args[ac], XmNheight, 221); ac++;
    mainSW = XmCreateScrolledWindow(mainPW,
        "mainSW",
        args, 
        ac);
    XtManageChild(mainSW);
    
    ac = 0;
    XtSetArg(args[ac], XmNadjustLast, False); ac++;
    XtSetArg(args[ac], XmNmarginWidth, 15); ac++;
    XtSetArg(args[ac], XmNmarginHeight, 15); ac++;
    XtSetArg(args[ac], XmNorientation, XmHORIZONTAL); ac++;
    XtSetArg(args[ac], XmNspacing, 20); ac++;
    XtSetArg(args[ac], XmNpacking, XmPACK_COLUMN); ac++;
    XtSetArg(args[ac], XmNwidth, 568); ac++;
    XtSetArg(args[ac], XmNheight, 221); ac++;
    mainRC = XmCreateRowColumn(mainSW,
        "mainRC",
        args, 
        ac);
    XtManageChild(mainRC);
    ccb_save_widget_id(mainRC, (XtPointer)GUI_MAIN_ROW_COL, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAPPLICATION_DEFINED); ac++;
    XtSetArg(args[ac], XmNwidth, 568); ac++;
    XtSetArg(args[ac], XmNheight, 330); ac++;
    main_resultSW = XmCreateScrolledWindow(mainPW,
        "main_resultSW",
        args, 
        ac);
    XtManageChild(main_resultSW);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    main_resultText = XmCreateText(main_resultSW,
        "main_resultText",
        args, 
        ac);
    XtManageChild(main_resultText);
    ccb_save_widget_id(main_resultText, (XtPointer)GUI_MAIN_RESULT_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 362); ac++;
    XtSetArg(args[ac], XmNheight, 577); ac++;
    dev_importDS = XtCreatePopupShell("dev_importDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 723); ac++;
    XtSetArg(args[ac], XmNy, 33); ac++;
    XtSetArg(args[ac], XmNwidth, 362); ac++;
    XtSetArg(args[ac], XmNheight, 577); ac++;
    dev_importForm = XmCreateForm(dev_importDS,
        "dev_importForm",
        args, 
        ac);
    ccb_save_widget_id(dev_importForm, (XtPointer)GUI_IMPORT_FORM, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 22); ac++;
    XtSetArg(args[ac], XmNy, 204); ac++;
    XtSetArg(args[ac], XmNwidth, 330); ac++;
    XtSetArg(args[ac], XmNheight, 365); ac++;
    dev_import_SelBox = XmCreateSelectionBox(dev_importForm,
        "dev_import_SelBox",
        args, 
        ac);
    XtManageChild(dev_import_SelBox);
    ccb_save_widget_id(dev_import_SelBox, (XtPointer)GUI_IMPORT_SELBOX, (XtPointer)0);
    ccb_dev_import_selbox(dev_import_SelBox, (XtPointer)0, (XtPointer)0);
    XtAddCallback(dev_import_SelBox, XmNhelpCallback, cb_fill_dev_selbox, (XtPointer)0);
    XtAddCallback(dev_import_SelBox, XmNokCallback, cb_device_import, (XtPointer)0);
    XtAddCallback(dev_import_SelBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"dev_importForm");
    XtUnmanageChild(XmSelectionBoxGetChild(dev_import_SelBox, XmDIALOG_APPLY_BUTTON));
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 9); ac++;
    XtSetArg(args[ac], XmNy, 170); ac++;
    XtSetArg(args[ac], XmNwidth, 336); ac++;
    XtSetArg(args[ac], XmNheight, 23); ac++;
    dev_importSep = XmCreateSeparator(dev_importForm,
        "dev_importSep",
        args, 
        ac);
    XtManageChild(dev_importSep);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 6); ac++;
    XtSetArg(args[ac], XmNwidth, 337); ac++;
    XtSetArg(args[ac], XmNheight, 160); ac++;
    dev_filterForm = XmCreateForm(dev_importForm,
        "dev_filterForm",
        args, 
        ac);
    XtManageChild(dev_filterForm);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 155); ac++;
    XtSetArg(args[ac], XmNy, 119); ac++;
    XtSetArg(args[ac], XmNwidth, 172); ac++;
    XtSetArg(args[ac], XmNheight, 35); ac++;
    memberText = XmCreateText(dev_filterForm,
        "memberText",
        args, 
        ac);
    XtManageChild(memberText);
    ccb_save_widget_id(memberText, (XtPointer)GUI_MEMBER_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 154); ac++;
    XtSetArg(args[ac], XmNy, 69); ac++;
    XtSetArg(args[ac], XmNwidth, 173); ac++;
    XtSetArg(args[ac], XmNheight, 35); ac++;
    familyText = XmCreateText(dev_filterForm,
        "familyText",
        args, 
        ac);
    XtManageChild(familyText);
    ccb_save_widget_id(familyText, (XtPointer)GUI_FAMILY_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 154); ac++;
    XtSetArg(args[ac], XmNy, 20); ac++;
    XtSetArg(args[ac], XmNwidth, 173); ac++;
    XtSetArg(args[ac], XmNheight, 35); ac++;
    domainText = XmCreateText(dev_filterForm,
        "domainText",
        args, 
        ac);
    XtManageChild(domainText);
    ccb_save_widget_id(domainText, (XtPointer)GUI_DOMAIN_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNx, 15); ac++;
    XtSetArg(args[ac], XmNy, 114); ac++;
    XtSetArg(args[ac], XmNwidth, 133); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    memberLabel = XmCreateLabel(dev_filterForm,
        "memberLabel",
        args, 
        ac);
    XtManageChild(memberLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNx, 15); ac++;
    XtSetArg(args[ac], XmNy, 66); ac++;
    XtSetArg(args[ac], XmNwidth, 133); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    familyLabel = XmCreateLabel(dev_filterForm,
        "familyLabel",
        args, 
        ac);
    XtManageChild(familyLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNx, 15); ac++;
    XtSetArg(args[ac], XmNy, 17); ac++;
    XtSetArg(args[ac], XmNwidth, 133); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    domainLabel = XmCreateLabel(dev_filterForm,
        "domainLabel",
        args, 
        ac);
    XtManageChild(domainLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 539); ac++;
    XtSetArg(args[ac], XmNheight, 135); ac++;
    confirmCloseDS = XtCreatePopupShell("confirmCloseDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_QUESTION); ac++;
    XtSetArg(args[ac], XmNx, 634); ac++;
    XtSetArg(args[ac], XmNy, 244); ac++;
    XtSetArg(args[ac], XmNwidth, 539); ac++;
    XtSetArg(args[ac], XmNheight, 135); ac++;
    confirmCloseMessBox = XmCreateMessageBox(confirmCloseDS,
        "confirmCloseMessBox",
        args, 
        ac);
    ccb_confirm_messbox(confirmCloseMessBox, (XtPointer)0, (XtPointer)0);
    XtAddCallback(confirmCloseMessBox, XmNokCallback, cb_close_device, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 295); ac++;
    XtSetArg(args[ac], XmNheight, 367); ac++;
    commandDS = XtCreatePopupShell("commandDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNlistItems, 
        CONVERT(parent, "item1  device server cmd,item2 device server cmd,item3 device server cmd,item4 device server cmd,item5 device server cmd,item6 device server cmd,item7 device server cmd", 
        XmRXmStringTable, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNlistItemCount, 7); ac++;
    XtSetArg(args[ac], XmNx, 756); ac++;
    XtSetArg(args[ac], XmNy, 128); ac++;
    XtSetArg(args[ac], XmNwidth, 295); ac++;
    XtSetArg(args[ac], XmNheight, 367); ac++;
    commandSelBox = XmCreateSelectionBox(commandDS,
        "commandSelBox",
        args, 
        ac);
    ccb_save_widget_id(commandSelBox, (XtPointer)GUI_COMMAND_SELBOX, (XtPointer)0);
    ccb_cmd_sel_box(commandSelBox, (XtPointer)0, (XtPointer)0);
    XtAddCallback(commandSelBox, XmNokCallback, cb_execute_cmd, (XtPointer)0);
    XtAddCallback(commandSelBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"commandSelBox");
    XtUnmanageChild(XtNameToWidget(commandSelBox, "*Apply"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 348); ac++;
    XtSetArg(args[ac], XmNheight, 285); ac++;
    dev_infoDS = XtCreatePopupShell("dev_infoDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 730); ac++;
    XtSetArg(args[ac], XmNy, 169); ac++;
    XtSetArg(args[ac], XmNwidth, 348); ac++;
    XtSetArg(args[ac], XmNheight, 285); ac++;
    dev_infoBB = XmCreateBulletinBoard(dev_infoDS,
        "dev_infoBB",
        args, 
        ac);
    ccb_save_widget_id(dev_infoBB, (XtPointer)GUI_DEVINFO_BB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 96); ac++;
    XtSetArg(args[ac], XmNy, 225); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 42); ac++;
    dismissPB = XmCreatePushButton(dev_infoBB,
        "dismissPB",
        args, 
        ac);
    XtManageChild(dismissPB);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 193); ac++;
    XtSetArg(args[ac], XmNwidth, 301); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    dev_infoSep = XmCreateSeparator(dev_infoBB,
        "dev_infoSep",
        args, 
        ac);
    XtManageChild(dev_infoSep);
    
    ac = 0;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 158); ac++;
    XtSetArg(args[ac], XmNy, 143); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    svc_hostText = XmCreateText(dev_infoBB,
        "svc_hostText",
        args, 
        ac);
    XtManageChild(svc_hostText);
    ccb_save_widget_id(svc_hostText, (XtPointer)GUI_DEVINFO_HOST_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNx, 23); ac++;
    XtSetArg(args[ac], XmNy, 145); ac++;
    XtSetArg(args[ac], XmNwidth, 120); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    svc_hostLabel = XmCreateLabel(dev_infoBB,
        "svc_hostLabel",
        args, 
        ac);
    XtManageChild(svc_hostLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 158); ac++;
    XtSetArg(args[ac], XmNy, 111); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    svc_nameText = XmCreateText(dev_infoBB,
        "svc_nameText",
        args, 
        ac);
    XtManageChild(svc_nameText);
    ccb_save_widget_id(svc_nameText, (XtPointer)GUI_DEVINFO_SERVNAME_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNx, 17); ac++;
    XtSetArg(args[ac], XmNy, 114); ac++;
    XtSetArg(args[ac], XmNwidth, 126); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    svc_nameLabel = XmCreateLabel(dev_infoBB,
        "svc_nameLabel",
        args, 
        ac);
    XtManageChild(svc_nameLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 158); ac++;
    XtSetArg(args[ac], XmNy, 79); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    dev_typeText = XmCreateText(dev_infoBB,
        "dev_typeText",
        args, 
        ac);
    XtManageChild(dev_typeText);
    ccb_save_widget_id(dev_typeText, (XtPointer)GUI_DEVINFO_TYPE_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 81); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    dev_typeLabel = XmCreateLabel(dev_infoBB,
        "dev_typeLabel",
        args, 
        ac);
    XtManageChild(dev_typeLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 158); ac++;
    XtSetArg(args[ac], XmNy, 46); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    dev_classText = XmCreateText(dev_infoBB,
        "dev_classText",
        args, 
        ac);
    XtManageChild(dev_classText);
    ccb_save_widget_id(dev_classText, (XtPointer)GUI_DEVINFO_CLASS_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNx, 19); ac++;
    XtSetArg(args[ac], XmNy, 48); ac++;
    XtSetArg(args[ac], XmNwidth, 124); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    dev_classLabel = XmCreateLabel(dev_infoBB,
        "dev_classLabel",
        args, 
        ac);
    XtManageChild(dev_classLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNhighlightThickness, 0); ac++;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 158); ac++;
    XtSetArg(args[ac], XmNy, 14); ac++;
    XtSetArg(args[ac], XmNwidth, 170); ac++;
    XtSetArg(args[ac], XmNheight, 31); ac++;
    dev_nameText = XmCreateText(dev_infoBB,
        "dev_nameText",
        args, 
        ac);
    XtManageChild(dev_nameText);
    ccb_save_widget_id(dev_nameText, (XtPointer)GUI_DEVINFO_NAME_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_END); ac++;
    XtSetArg(args[ac], XmNx, 20); ac++;
    XtSetArg(args[ac], XmNy, 16); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 24); ac++;
    dev_nameLabel = XmCreateLabel(dev_infoBB,
        "dev_nameLabel",
        args, 
        ac);
    XtManageChild(dev_nameLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 340); ac++;
    XtSetArg(args[ac], XmNheight, 322); ac++;
    help_versionDS = XtCreatePopupShell("help_versionDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 734); ac++;
    XtSetArg(args[ac], XmNy, 150); ac++;
    XtSetArg(args[ac], XmNwidth, 340); ac++;
    XtSetArg(args[ac], XmNheight, 322); ac++;
    help_versionBB = XmCreateBulletinBoard(help_versionDS,
        "help_versionBB",
        args, 
        ac);
    ccb_save_widget_id(help_versionBB, (XtPointer)GUI_HELP_VERS_BB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 110); ac++;
    XtSetArg(args[ac], XmNy, 260); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 42); ac++;
    version_dismissPB = XmCreatePushButton(help_versionBB,
        "version_dismissPB",
        args, 
        ac);
    XtManageChild(version_dismissPB);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 320); ac++;
    XtSetArg(args[ac], XmNheight, 233); ac++;
    help_versionText = XmCreateText(help_versionBB,
        "help_versionText",
        args, 
        ac);
    XtManageChild(help_versionText);
    ccb_save_widget_id(help_versionText, (XtPointer)GUI_HELP_VERS_TEXT, (XtPointer)0);
    ccb_help_version_text(help_versionText, (XtPointer)0, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 485); ac++;
    XtSetArg(args[ac], XmNheight, 115); ac++;
    errorDS = XtCreatePopupShell("errorDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNmessageString, 
        CONVERT(parent, "This is an error message! An error has just happened.", 
        XmRXmString, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNx, 661); ac++;
    XtSetArg(args[ac], XmNy, 254); ac++;
    XtSetArg(args[ac], XmNwidth, 485); ac++;
    XtSetArg(args[ac], XmNheight, 115); ac++;
    errorMessBox = XmCreateMessageBox(errorDS,
        "errorMessBox",
        args, 
        ac);
    ccb_save_widget_id(errorMessBox, (XtPointer)GUI_ERROR_WINDOW, (XtPointer)0);
    ccb_error_messbox(errorMessBox, (XtPointer)0, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 547); ac++;
    XtSetArg(args[ac], XmNheight, 387); ac++;
    help_appliDS = XtCreatePopupShell("help_appliDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 630); ac++;
    XtSetArg(args[ac], XmNy, 118); ac++;
    XtSetArg(args[ac], XmNwidth, 547); ac++;
    XtSetArg(args[ac], XmNheight, 387); ac++;
    help_appliBB = XmCreateBulletinBoard(help_appliDS,
        "help_appliBB",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAPPLICATION_DEFINED); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 26); ac++;
    XtSetArg(args[ac], XmNwidth, 525); ac++;
    XtSetArg(args[ac], XmNheight, 295); ac++;
    help_appliSW = XmCreateScrolledWindow(help_appliBB,
        "help_appliSW",
        args, 
        ac);
    XtManageChild(help_appliSW);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    help_appli_text = XmCreateText(help_appliSW,
        "help_appli_text",
        args, 
        ac);
    XtManageChild(help_appli_text);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 211); ac++;
    XtSetArg(args[ac], XmNy, 329); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 42); ac++;
    appli_dismissPB = XmCreatePushButton(help_appliBB,
        "appli_dismissPB",
        args, 
        ac);
    XtManageChild(appli_dismissPB);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 412); ac++;
    XtSetArg(args[ac], XmNheight, 151); ac++;
    ch_timeoutDS = XtCreatePopupShell("ch_timeoutDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_PROMPT); ac++;
    XtSetArg(args[ac], XmNx, 698); ac++;
    XtSetArg(args[ac], XmNy, 236); ac++;
    XtSetArg(args[ac], XmNwidth, 412); ac++;
    XtSetArg(args[ac], XmNheight, 151); ac++;
    ch_timeout_selbox = XmCreateSelectionBox(ch_timeoutDS,
        "ch_timeout_selbox",
        args, 
        ac);
    ccb_timeout_prompt(ch_timeout_selbox, (XtPointer)0, (XtPointer)0);
    ccb_save_widget_id(ch_timeout_selbox, (XtPointer)GUI_TIMEOUT_SELBOX, (XtPointer)0);
    XtAddCallback(ch_timeout_selbox, XmNokCallback, cb_change_timeout, (XtPointer)0);
    XtUnmanageChild(XtNameToWidget(ch_timeout_selbox, "*Apply"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 531); ac++;
    XtSetArg(args[ac], XmNheight, 310); ac++;
    help_dataDS = XtCreatePopupShell("help_dataDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 638); ac++;
    XtSetArg(args[ac], XmNy, 156); ac++;
    XtSetArg(args[ac], XmNwidth, 531); ac++;
    XtSetArg(args[ac], XmNheight, 310); ac++;
    help_dataBB = XmCreateBulletinBoard(help_dataDS,
        "help_dataBB",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 212); ac++;
    XtSetArg(args[ac], XmNy, 252); ac++;
    XtSetArg(args[ac], XmNwidth, 123); ac++;
    XtSetArg(args[ac], XmNheight, 42); ac++;
    help_data_dismissPB = XmCreatePushButton(help_dataBB,
        "help_data_dismissPB",
        args, 
        ac);
    XtManageChild(help_data_dismissPB);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNautoShowCursorPosition, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 502); ac++;
    XtSetArg(args[ac], XmNheight, 233); ac++;
    help_dataText = XmCreateText(help_dataBB,
        "help_dataText",
        args, 
        ac);
    XtManageChild(help_dataText);
    ccb_save_widget_id(help_dataText, (XtPointer)GUI_INARG_FORMAT_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 653); ac++;
    XtSetArg(args[ac], XmNheight, 193); ac++;
    in_argDS = XtCreatePopupShell("in_argDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNautoUnmanage, False); ac++;
    XtSetArg(args[ac], XmNx, 578); ac++;
    XtSetArg(args[ac], XmNy, 215); ac++;
    inarg_form = XmCreateForm(in_argDS,
        "inarg_form",
        args, 
        ac);
    ccb_save_widget_id(inarg_form, (XtPointer)GUI_INARG_WIN, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 518); ac++;
    XtSetArg(args[ac], XmNy, 147); ac++;
    XtSetArg(args[ac], XmNwidth, 107); ac++;
    XtSetArg(args[ac], XmNheight, 36); ac++;
    cancelPB = XmCreatePushButton(inarg_form,
        "cancelPB",
        args, 
        ac);
    XtManageChild(cancelPB);
    XtAddCallback(cancelPB, XmNactivateCallback, BxUnmanageCB, (XtPointer)"inarg_form");
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 264); ac++;
    XtSetArg(args[ac], XmNy, 147); ac++;
    XtSetArg(args[ac], XmNwidth, 91); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    helpPB = XmCreatePushButton(inarg_form,
        "helpPB",
        args, 
        ac);
    XtManageChild(helpPB);
    XtAddCallback(helpPB, XmNactivateCallback, BxManageCB, (XtPointer)"help_dataBB");
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 17); ac++;
    XtSetArg(args[ac], XmNy, 148); ac++;
    XtSetArg(args[ac], XmNwidth, 165); ac++;
    XtSetArg(args[ac], XmNheight, 35); ac++;
    executePB = XmCreatePushButton(inarg_form,
        "executePB",
        args, 
        ac);
    XtManageChild(executePB);
    XtAddCallback(executePB, XmNactivateCallback, BxUnmanageCB, (XtPointer)"inarg_form");
    XtAddCallback(executePB, XmNactivateCallback, cb_execute_cmd_input, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAPPLICATION_DEFINED); ac++;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 45); ac++;
    XtSetArg(args[ac], XmNwidth, 626); ac++;
    XtSetArg(args[ac], XmNheight, 92); ac++;
    inarg_value_sw = XmCreateScrolledWindow(inarg_form,
        "inarg_value_sw",
        args, 
        ac);
    XtManageChild(inarg_value_sw);
    
    ac = 0;
    XtSetArg(args[ac], XmNbackground, 
        CONVERT(parent, "White Smoke", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNforeground, 
        CONVERT(parent, "Black", 
        XmRPixel, 0, &argok)); if (argok) ac++;
    XtSetArg(args[ac], XmNvalue, ""); ac++;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNfontList, 
        CONVERT(parent, "-*-helvetica-bold-r-*-*-*-140-75-75-*-*-iso8859-1", 
        XmRFontList, 0, &argok)); if (argok) ac++;
    inarg_value_text = XmCreateText(inarg_value_sw,
        "inarg_value_text",
        args, 
        ac);
    XtManageChild(inarg_value_text);
    ccb_save_widget_id(inarg_value_text, (XtPointer)GUI_INARG_VAL_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNshadowThickness, 0); ac++;
    XtSetArg(args[ac], XmNvalue, ""); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNx, 6); ac++;
    XtSetArg(args[ac], XmNy, 6); ac++;
    XtSetArg(args[ac], XmNwidth, 606); ac++;
    XtSetArg(args[ac], XmNheight, 34); ac++;
    in_name_text = XmCreateText(inarg_form,
        "in_name_text",
        args, 
        ac);
    XtManageChild(in_name_text);
    ccb_save_widget_id(in_name_text, (XtPointer)GUI_INARG_NAME_TEXT, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 359); ac++;
    XtSetArg(args[ac], XmNheight, 152); ac++;
    confirmExitDS = XtCreatePopupShell("confirmExitDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_QUESTION); ac++;
    XtSetArg(args[ac], XmNx, 724); ac++;
    XtSetArg(args[ac], XmNy, 235); ac++;
    XtSetArg(args[ac], XmNwidth, 359); ac++;
    XtSetArg(args[ac], XmNheight, 152); ac++;
    confirmExitMessBox = XmCreateMessageBox(confirmExitDS,
        "confirmExitMessBox",
        args, 
        ac);
    ccb_confirm_messbox(confirmExitMessBox, (XtPointer)0, (XtPointer)0);
    XtAddCallback(confirmExitMessBox, XmNokCallback, BxExitCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 290); ac++;
    XtSetArg(args[ac], XmNheight, 204); ac++;
    protocolDS = XtCreatePopupShell("protocolDS",
        xmDialogShellWidgetClass,
        mainWindow,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 759); ac++;
    XtSetArg(args[ac], XmNy, 209); ac++;
    XtSetArg(args[ac], XmNwidth, 290); ac++;
    XtSetArg(args[ac], XmNheight, 204); ac++;
    protocolBB = XmCreateBulletinBoard(protocolDS,
        "protocolBB",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 198); ac++;
    XtSetArg(args[ac], XmNy, 134); ac++;
    XtSetArg(args[ac], XmNwidth, 80); ac++;
    XtSetArg(args[ac], XmNheight, 39); ac++;
    cancelPB1 = XmCreatePushButton(protocolBB,
        "cancelPB1",
        args, 
        ac);
    XtManageChild(cancelPB1);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 13); ac++;
    XtSetArg(args[ac], XmNy, 135); ac++;
    XtSetArg(args[ac], XmNwidth, 114); ac++;
    XtSetArg(args[ac], XmNheight, 39); ac++;
    setPB = XmCreatePushButton(protocolBB,
        "setPB",
        args, 
        ac);
    XtManageChild(setPB);
    XtAddCallback(setPB, XmNactivateCallback, cb_protocol_change, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 97); ac++;
    XtSetArg(args[ac], XmNwidth, 269); ac++;
    XtSetArg(args[ac], XmNheight, 20); ac++;
    protocolSEP = XmCreateSeparator(protocolBB,
        "protocolSEP",
        args, 
        ac);
    XtManageChild(protocolSEP);
    
    ac = 0;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    XtSetArg(args[ac], XmNradioAlwaysOne, False); ac++;
    XtSetArg(args[ac], XmNx, 75); ac++;
    XtSetArg(args[ac], XmNy, 18); ac++;
    XtSetArg(args[ac], XmNwidth, 66); ac++;
    XtSetArg(args[ac], XmNheight, 65); ac++;
    protocolRBox = XmCreateRadioBox(protocolBB,
        "protocolRBox",
        args, 
        ac);
    XtManageChild(protocolRBox);
    ccb_save_widget_id(protocolRBox, (XtPointer)GUI_PROTOCOL_RB, (XtPointer)0);
    XtAddCallback(protocolRBox, XmNentryCallback, cb_protocol_entry, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 60); ac++;
    XtSetArg(args[ac], XmNheight, 28); ac++;
    tcpTB = XmCreateToggleButton(protocolRBox,
        "tcpTB",
        args, 
        ac);
    XtManageChild(tcpTB);
    ccb_save_widget_id(tcpTB, (XtPointer)GUI_TCP_TB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 60); ac++;
    XtSetArg(args[ac], XmNheight, 28); ac++;
    udpTB = XmCreateToggleButton(protocolRBox,
        "udpTB",
        args, 
        ac);
    XtManageChild(udpTB);
    ccb_save_widget_id(udpTB, (XtPointer)GUI_UDP_TB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNmenuBar, menuBar); ac++;
    XtSetValues(mainWindow, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNinitialFocus, inarg_value_sw); ac++;
    XtSetValues(inarg_form, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 10); ac++;
    XtSetArg(args[ac], XmNrightOffset, 28); ac++;
    XtSetValues(cancelPB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 0); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 6); ac++;
    XtSetArg(args[ac], XmNleftOffset, 264); ac++;
    XtSetValues(helpPB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 10); ac++;
    XtSetArg(args[ac], XmNleftOffset, 17); ac++;
    XtSetValues(executePB, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopWidget, in_name_text); ac++;
    XtSetArg(args[ac], XmNbottomWidget, helpPB); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 10); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 22); ac++;
    XtSetValues(inarg_value_sw, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 6); ac++;
    XtSetArg(args[ac], XmNleftOffset, 6); ac++;
    XtSetArg(args[ac], XmNrightOffset, 41); ac++;
    XtSetValues(in_name_text, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 204); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 8); ac++;
    XtSetArg(args[ac], XmNleftOffset, 22); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetValues(dev_import_SelBox, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 170); ac++;
    XtSetArg(args[ac], XmNleftOffset, 9); ac++;
    XtSetArg(args[ac], XmNrightOffset, 17); ac++;
    XtSetValues(dev_importSep, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 6); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNrightOffset, 15); ac++;
    XtSetValues(dev_filterForm, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 119); ac++;
    XtSetArg(args[ac], XmNleftOffset, 155); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetValues(memberText, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 69); ac++;
    XtSetArg(args[ac], XmNleftOffset, 154); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetValues(familyText, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 20); ac++;
    XtSetArg(args[ac], XmNleftOffset, 154); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetValues(domainText, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 114); ac++;
    XtSetArg(args[ac], XmNleftOffset, 15); ac++;
    XtSetValues(memberLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 66); ac++;
    XtSetArg(args[ac], XmNleftOffset, 15); ac++;
    XtSetValues(familyLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNtopOffset, 17); ac++;
    XtSetArg(args[ac], XmNleftOffset, 15); ac++;
    XtSetValues(domainLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNmenuHelpWidget, helpCB); ac++;
    XtSetValues(menuBar, args, ac);
    
    return( mainWindow );
}
