/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * Created by Builder Xcessory 4.0
 * Generated by Code Generator Xcessory 2.0 (09/09/96)
 *
 */
#ifndef greta_cstes_H
#define greta_cstes_H
#define bool_opIDsNb 4
#define ServSelectionTFID 27
#define ServNameTextID 41
#define PersNameTextID 42
#define QuitMsgBoxID 15
#define InfoBoxID 2
#define DevDelOpFormID 24
#define PrintFormID 4
#define FileLoadTextID 39
#define ServDelNWResTBID 20
#define StdinoutTextID 21
#define ServUpdateBoxID 33
#define ResMembListID 22
#define ServSelFormID 25
#define servdisplay_embedded 1
#define MemberListID 14
#define ResNameListID 23
#define ErrorBoxID 8
#define ResDomListID 32
#define LoadFileSelBoxID 37
#define ResFamListID 1
#define ResSelFormID 30
#define servdisplay_classresID 0
#define LpOptionsTextFID 7
#define ServFilterTFID 26
#define ClassListID 3
#define SaveFileSelBoxID 36
#define DevDelNWResTBID 19
#define PnameListID 16
#define ServDelOpFormID 28
#define FileLoadFormID 38
#define A2psOptionsTextFID 6
#define PasswdTextID 40
#define CopiesNbTextFID 5
#define DevSelectionTFID 11
#define ServDelWResTBID 18
#define DevDelWResTBID 17
#define ServUnregBoxID 29
#define FamilyListID 13
#define WidgetIDsNb 50
#define ServRestartBoxID 44
#define DomainListID 12
#define devdisplay_dc 2
#define DevSelFormID 9
#define devdisplay_hdb 3
#define MainTextID 0
#define DevUpdateBoxID 34
#define ResUpdateBoxID 35
#define DevFilterTFID 10
#define ResFilterTFID 31
#define DevListTextID 43
#endif
